

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: frontend
    spec:
      containers:
        - name: frontend
          image: kishore8856/frontend:v2
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 300
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "100m"
              memory: "150Mi"
          volumeMounts:
            - name: frontend-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

      volumes:
        - name: frontend-conf
          configMap:
            name: frontend-cm
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80    # port on which service is exposed
      targetPort: 8080   # port on which container is listening

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70




  
