apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: payment
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: payment
    spec:
      containers:
        - name: payment
          image: kishore8856/payment:v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: payment
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 150
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: payment
  ports:
    - protocol: TCP
      port: 8080    # port on which service is exposed
      targetPort: 8080   # port on which container is listening

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: payment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70




  
