apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: shipping
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: shipping
    spec:
      containers:
        - name: shipping
          image: kishore8856/shipping:v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: shipping
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 25
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "100m"
              memory: "150Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: shipping
  ports:
    - protocol: TCP
      port: 8080    # port on which service is exposed
      targetPort: 8080   # port on which container is listening

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: shipping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70




  
