# Normal service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017    # port on which service is exposed
      targetPort: 27017   # port on which mongodb container is listening

---
# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
reclaimPolicy: Delete      # Volume along with data will be retained even after PVC deletion, Delete- volume is deleted when pvc is deleted
provisioner: ebs.csi.aws.com  # Uses AWS EBS CSI driver for dynamically create PVs
volumeBindingMode: WaitForFirstConsumer 

---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mongodb 
  serviceName: "mongodb-headless"   #This should be headless service name
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: kishore8856/mongodb:v2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # This is PVC
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
