# Normal service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: mongodb
  ports:
    - protocol: TCP
      port: 6379    # port on which service is exposed
      targetPort: 6379   # port on which mongodb container is listening

---
# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: redis 
  serviceName: "redis-headless"   #This should be headless service name
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis
          mountPath: /data
  # This is PVC
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
